# Generated by Django 6.0 on 2025-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_options_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('open', 'Open Ended')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
