# Generated by Django 6.0 on 2025-12-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_correct_text_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_text',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='multiple_choice', max_length=50),
        ),
    ]
